### ISSUE TITLE
Not working in Windows

### ISSUE THREAD

**Issue by mbuceta** [cemerick/url#1]
The library won't load in Windows, just making a require will throw an error.

This is a problem with pathetic, see https://github.com/davidsantiago/pathetic/issues/2

**Comment by davidsantiago** [comment]
This should be fixable with no code changes in url by simply updating to version 0.4.0 of pathetic.

**Comment by cemerick** [comment]
Fix for this available in `[com.cemerick/url "0.0.4"]`.  Thanks for the report! :-)
