### ISSUE TITLE
no support for root-relative urls

### ISSUE THREAD

**Issue by dustingetz** [cemerick/url#15]
``` clojure
ClojureScript:cljs.user> (str (cemerick.url/url "/asdf"))
":///asdf"
```

which is not something that a browser can understand.

**Comment by kernelp4nic** [comment]
this would be great!

**Comment by cemerick** [comment]
I assume you're hoping that expression would yield `"/asdf"`? That's not a URL, it's a path.

Absolute paths are resolved properly AFAICT:

``` clojure
user=> (str (url "http://example.com/foo/bar/baz" "/quux"))
"http://example.com/quux"
```
