### ISSUE TITLE
support url split on percent encoded slash

### ISSUE THREAD

**Issue by ccfontes** [cemerick/url#16]
The url is not split in correct parts if "/" is percent encoded (%2F). Would it be nice to support percent encoded slashes?

**Comment by cemerick** [comment]
If we did this, then you couldn't have portions of a path contain URL-encoded slashes. It sounds like you need to decode certain portions of the path, and then reconstruct the URL.

**Comment by ccfontes** [comment]
Why couldn't I have encoded slashes as well as decoded slashes in portions of a path?
