### ISSUE TITLE
query

### ISSUE THREAD

**Issue by siscia** [cemerick/url#2]
Is really necessary in my opinion something like that:
=>(str (url "http://www.saltycrane.com/blog/2011/11/unique-python-redis-based-queue-delay/ :query {:a 3, :b 4}))
;; "http://www.saltycrane.com/blog/2011/11/unique-python-redis-based-queue-delay/a=3&b=4"
That is different from
=> (str (assoc *2 :query {:a 5 :b 6}))
"https://api.twitter.com/1/users/profile_image/cemerick?a=5&b=6"

**Comment by cemerick** [comment]
`url` has never taken a `:query` kwarg like that.  I think you mean:

``` clojure
=> (-> (url "http://www.saltycrane.com/blog/2011/11/unique-python-redis-based-queue-delay/")
     (assoc :query {:a 3, :b 4})
     str)
"http://www.saltycrane.com/blog/2011/11/unique-python-redis-based-queue-delay?a=3&b=4"
```

That result seems right to me?

**Comment by siscia** [comment]
Yeah, ok, I just saying that in my opinion would be better give the opportunity to use url with the :query kwarg, i think will be smoother and simpler... It is just an opinion, what you think ?

**Comment by cemerick** [comment]
Oh, I see what you're getting at.  This would be best implemented as a thin wrapper on top of `map->URL`, and seems like a decent idea.  `url`'s main job will definitely continue to be the glomming together of URL parts (analogous to `clojure.java.io/file`).
