### ISSUE TITLE
:path forgets "/"

### ISSUE THREAD

**Issue by dehubbed** [cemerick/url#4]
=> (str (assoc (cemerick.url/url "https://XXX.cloudant.com/") :path "databasename"))
"https://XXX.cloudant.comdatabasename"

LOL

The example is from the clutch README.md, i.e. clutch is broken by extension.

**Comment by cemerick** [comment]
Fixed in https://github.com/cemerick/url/commit/ad4841145271161a8c5cd5f78952367be25ad5a3

The clutch example is wrong, regardless of this issue; assoc'ing a :path into a url will always blow away what's there already.
